package jp.horimislime.weblogger.server.db.mapper;

import java.util.List;
import java.util.Map;

import jp.horimislime.weblogger.server.db.Log;
import jp.horimislime.weblogger.server.db.LogExample;

import org.apache.ibatis.annotations.Param;

public interface LogMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int countByExample(LogExample example);

	/**
	 * 
	 * Get total count of page access for each day
	 * 
	 */
	List<Map<String, Object>> countByDay(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int deleteByExample(LogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int insert(Log record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int insertSelective(Log record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	List<Log> selectByExample(LogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	Log selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int updateByExampleSelective(@Param("record") Log record, @Param("example") LogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int updateByPrimaryKeySelective(Log record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table log
	 * 
	 * @mbggenerated Sat Jul 07 12:14:46 JST 2012
	 */
	int updateByPrimaryKey(Log record);
}